Update armbian-build
added getopts and options arg handelng

diff --git a/armbian-build b/armbian-build
--- a/armbian-build
+++ b/armbian-build
@@ -1,6 +1,7 @@
-#!/usr/bin/env bash
+#!/bin/bash
 #
 # SPDX-License-Identifier: GPL-2.0
+#
 #
 # This file is a part of the Armbian Build Framework
 # https://github.com/armbian/build/
@@ -13,32 +14,16 @@ system_language=$(locale | grep LANG | cut -d= -f2)
 # More than one command can map to the same handler. In that case, use ARMBIAN_COMMANDS_TO_VARS_DICT for specific vars.
 declare -g -A ARMBIAN_COMMANDS_TO_HANDLERS_DICT=(
         ["docker"]="docker" # thus requires cli_docker_pre_run and cli_docker_run
-)
-
-# docker
-ARMBIAN_COMMANDS_TO_HANDLERS_DICT+=(
-
 		["docker-purge"]="docker"
 		["dockerpurge"]="docker"
 		["docker-shell"]="docker"
 		["dockershell"]="docker"
 		["generate-dockerfile"]="docker"
-)
-
-# implemented in cli_requirements_pre_run and cli_requirements_run
-ARMBIAN_COMMANDS_TO_HANDLERS_DICT+=(
 		["requirements"]="requirements" # implemented in cli_requirements_pre_run and cli_requirements_run
-)
-
-# Given a board/config/exts, dump out the (non-userspace) JSON of configuration
-ARMBIAN_COMMANDS_TO_HANDLERS_DICT+=(
 		["configdump"]="config_dump_json"
 		["config-dump"]="config_dump_json"
 		["config-dump-json"]="config_dump_json"
 		["config-dump-no-json"]="config_dump_json"
-		)
-# implemented in cli_json_info_pre_run and cli_json_info_run
-ARMBIAN_COMMANDS_TO_HANDLERS_DICT+=(
 		["inventory"]="json_info"
 		["targets"]="json_info"
 		["targets-dashboard"]="json_info"
@@ -47,11 +32,6 @@ ARMBIAN_COMMANDS_TO_HANDLERS_DICT+=(
 		["gha-matrix"]="json_info"
 		["gha-workflow"]="json_info"
 		["gha-template"]="json_info"
-)
-
-# These probably should be in their own separate CLI commands file, but for now they're together in jsoninfo.
-ARMBIAN_COMMANDS_TO_HANDLERS_DICT+=(
-
 		["debs-to-repo-download"]="json_info" # implemented in cli_json_info_pre_run and cli_json_info_run
 		["debs-to-repo-reprepro"]="json_info" # implemented in cli_json_info_pre_run and cli_json_info_run
 
@@ -62,12 +42,6 @@ ARMBIAN_COMMANDS_TO_HANDLERS_DICT+=(
 		["distccd"]="distccd"      # implemented in cli_distccd_pre_run and cli_distccd_run
 		["flash"]="flash"          # implemented in cli_flash_pre_run and cli_flash_run
 )
-
-# TO add new groups if needed
-#ARMBIAN_COMMANDS_TO_HANDLERS_DICT+=(
-#
-#)
-
 
 # EN ARMBIAN_COMMANDS_TO_HANDLERS_DICT Descritions Groups
 declare -A COMMAND_DESCRIPTIONS_EN=(
@@ -127,89 +101,73 @@ declare -A COMMAND_DESCRIPTIONS_ES=(
     ["flash"]="..."
 )
 
-set_interface(){
-    local i=0
+# Set default language to English
+COMMAND_DESCRIPTIONS=("${COMMAND_DESCRIPTIONS_EN[@]}")
 
-    # Set default language to English
-    COMMAND_DESCRIPTIONS=("${COMMAND_DESCRIPTIONS_EN[@]}")
+# Choose array based on system language
+if [[ $system_language == "de"* ]]; then
+    COMMAND_DESCRIPTIONS=("${COMMAND_DESCRIPTIONS_DE[@]}")
+elif [[ $system_language == "es"* ]]; then
+    COMMAND_DESCRIPTIONS=("${COMMAND_DESCRIPTIONS_ES[@]}")
+fi
 
-    # Choose array based on system language
-    if [[ $system_language == "de"* ]]; then
-        COMMAND_DESCRIPTIONS=("${COMMAND_DESCRIPTIONS_DE[@]}")
-    elif [[ $system_language == "es"* ]]; then
-        COMMAND_DESCRIPTIONS=("${COMMAND_DESCRIPTIONS_ES[@]}")
-    fi
 
-    # Set numbered array
-    for key in "${!ARMBIAN_COMMANDS_TO_HANDLERS_DICT[@]}"; do
-        description=${COMMAND_DESCRIPTIONS[${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$key]}]}
-        help_set+=("$(printf '\t%s  -  %s\n' "$key" "$description")")
-        display_set+=("$(printf '%d %s - %s' "$i" "$key" "$description")")
-        menu_set+=("$(printf '%d %s - %s' "$i" "$key" "$description")")
-        array_set+=("$(printf '%d [%s]=%s' "$i" "$key" "${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$key]}")")
-        ((++i))
+
+generate_descriptions() {
+    local i=1
+    local command
+    local description
+
+    for command in "${!ARMBIAN_COMMANDS_TO_HANDLERS_DICT[@]}"; do
+        description="${COMMAND_DESCRIPTIONS_EN[${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$command]}]}"
+        handler="${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$command]}"
+        printf '%d %s  - %s\n    ["%s"]="%s"\n' "$i" "$command" "$description" "$command" "$handler"
+        ((i++))
     done
-
 }
 
-see_all(){
+generate_help_message() {
+    local i=1
+    local command
+    local description
 
-	set_interface
-
-    for item in "${display_set[@]}"; do
-        printf '%s\n' "$item"
+    for command in "${!ARMBIAN_COMMANDS_TO_HANDLERS_DICT[@]}"; do
+        description="${COMMAND_DESCRIPTIONS_EN[${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$command]}]}"
+        handler="${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$command]}"
+        printf '%s  - %s\n    ["%s"]="%s"\n\n' "$command" "$description" "$command" "$handler"
+        ((i++))
     done
-
 }
 
-help_all(){
+generate_results() {
+    local i=1
+    local command
+    local description
 
-	set_interface
-
-    for item in "${help_set[@]}"; do
-        printf '%s\n' "$item"
+    for command in "${!ARMBIAN_COMMANDS_TO_HANDLERS_DICT[@]}"; do
+        description=${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$command]}
+        printf '  ["%s"]="%s"\n'  "$command" "$description"
+        ((i++))
     done
-
 }
 
-read_all(){
 
-    set_interface
+# Call the function
+while getopts "hr" opt; do
+    case "$opt" in
+	h)  generate_help_message
+		;;
+    r)
+        generate_results
+        ;;
+    esac
+done
 
-    # Print the array
-    for item in "${display_set[@]}"; do
-        echo "$item"
-    done
-
-	read -p "Select an option (enter the number): " choice ;
-
-	clear && process_selection "$choice" ;
-
-}
-
-# pre set for tui proposel
-tui_all(){
-
-	set_interface
-
-    # Print the array
-	for item in "${menu_set[@]}"; do
-	    echo "$item"
-	done | configng-interface -m ;
-	
-    process_selection "$1" | configng-interface -o
-}
-
-process_selection(){
-    local selected_item="$1"
-    local option="${array_set[$selected_item]}"
-    echo "${option#* }"
-}
-
-# Generic output
-
-[[ -z "$@" ]] && help_all
-
-[[ "$1" == "-t" ]] && tui_all
-
-[[ "$1" == "-r" ]] && read_all
+if [[ $1 == *"--"* ]]; then
+    echo "Error: Invalid option detected"
+    exit 1
+elif [[ -n $1 && $1 != "--" ]]; then
+    bash ./compile.sh "$@"
+elif [[ -z $1 ]]; then
+    generate_descriptions
+fi
